version: '3.8'

services:
  postgres1:
    image: postgres:14
    container_name: bananzza
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata1:/var/lib/postgresql/data
    networks:
      - goapp-network

  postgres2:
    image: postgres:14
    container_name: lasciva
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lasciva
    ports:
      - "5433:5432"  # Пробрасываем на другой порт на хосте
    volumes:
      - pgdata2:/var/lib/postgresql/data
    networks:
      - goapp-network
  postgres3:
    image: postgres:14
    container_name: wisteria
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wisteria
    ports:
      - "5434:5432"  # Пробрасываем на другой порт на хосте
    volumes:
      - pgdata3:/var/lib/postgresql/data
    networks:
      - goapp-network

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
    networks:
      - goapp-network

volumes:
  pgdata1:
  pgdata2:
  pgdata3:

networks:
  goapp-network:
    driver: bridge
